import { createList } from "./linkedList";
import { createTree } from "./binaryTree";

let newTree = createTree();
// console.log(newTree.inOrder(newTree.getRoot()));
newTree.append("F");
// console.log(newTree.inOrder(newTree.getRoot()));
newTree.append("D");
// console.log(newTree.inOrder(newTree.getRoot()));
newTree.append("J");
newTree.append("B");
newTree.append("E");
newTree.append("G");
newTree.append("K");
newTree.append("A");
newTree.append("C");
newTree.append("I");
newTree.append("H");
console.log(newTree.breadthTraverse(newTree.getRoot()));
// console.log(newTree.inOrder(newTree.getRoot()));
// console.log(newTree.preOrder(newTree.getRoot()));
// console.log(newTree.postOrder(newTree.getRoot()));