import { createList } from "./linkedList";
import { createTree } from "./binaryTree";


// let newList = createList();
// newList.append(1);
// newList.append(2);
// newList.append(3);
// newList.append(4);
// newList.append(5);
// console.log(newList.toString());
// newList.insertAt(2, 6);
// console.log(newList.toString());
// newList.insertAt(0, 7);
// console.log(newList.toString());
// newList.insertAt(2, 8);
// console.log(newList.toString());
// newList.remove(0);
// console.log(newList.toString());
// newList.remove(2);
// console.log(newList.toString());
// newList.remove(5);
// console.log(newList.toString());
let newTree = createTree();
newTree.insert("F");
newTree.insert("D");
newTree.insert("J");
newTree.insert("B");
newTree.insert("E");
newTree.insert("G");
newTree.insert("K");
newTree.insert("A");
newTree.insert("C");
newTree.insert("I");
newTree.insert("H");
// console.log(newTree.levelOrder(newTree.getRoot()));
// console.log(newTree.height("F"));
// console.log(newTree.levelOrder(newTree.getRoot()));
let arr = [];
newTree.postOrder(newTree.getRoot(), arr);
console.log(arr);
// console.log(newTree.preOrder(newTree.getRoot()));
// console.log(newTree.postOrder(newTree.getRoot()));